Public Class DocArrecad
    Public KKY As String
    Public Filial As String
    Public DTH_REGISTRO As String
    Public NUM_DOCTO_CLIENTE As String
    Public NOM_DOCTO_CLIENTE As String
    Public NUM_DA As String
    Public NUM_SEQ_DA As String
    Public NUM_DV_DA As String
    Public TIP_NATUREZA_PESSOA As String
    Public NOM_BAIRRO As String
    Public NUM_CEP As String
    Public NOM_CIDADE As String
    Public END_LOGRADOURO As String
    Public END_NUMERO As String
    Public END_COMPLEMENTO As String
    Public SIG_UNIDADE_FEDERACAO As String
    Public NUM_TELEFONE As String
    Public NOM_END_EMAIL As String
    Public COD_NATUREZA_CLI As String
    Public COD_ATIVIDADE_ECONOMICA As String
    Public COD_MUNICIPIO_IBGE As String
    Public NUM_INSCR_MUNICIPAL As String
    Public NUM_INSCR_ESTADUAL As String
    Public SIG_PAIS As String
    Public TIP_OPERACAO As String
    Public TIP_STATUS_PAGTO As String
    Public TIP_DOCUMENTO As String
    Public COD_BANCO As String
    Public DAT_EMISSAO As String
    Public DAT_PAGTO As String
    Public DAT_VENCTO As String
    Public VAL_TARIFA As Decimal
    Public VAL_ATAERO As Decimal
    Public VAL_RETENCAO As Decimal
    Public VAL_DEVIDO As Decimal
    Public VAL_PAGO As Decimal
    Public VAL_TOTAL_DA As Decimal
    Public DSC_SERVICO As String
    Public NUM_QUANTIDADE As Integer
    Public VAL_SERVICO As Decimal
    Public TXT_ORIGEM_DA As String
    Public DAT_RECEBIMENTO_CARGA As String
    Public DTH_INICIO_SERVICO As String
    Public DTH_FIM_SERVICO As String
    Public DAT_ENTREGA_CARGA As String
End Class
